#!/usr/bin/env python3
"""Export verified padron from Firestore verification results.

Pulls verified results from Firestore, merges them with the original
tasks.json OCR data, and produces the final verified padron JSON/CSV.

Usage:
    python -m tools.export_verified
    python -m tools.export_verified --include-unverified --format csv
    python -m tools.export_verified --stats
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent / "13_mayo_2026" / "padron_provisorio"
TASKS_FILE = BASE_DIR / "webapp" / "public" / "data" / "verificacion" / "tasks.json"
DEFAULT_OUTPUT = BASE_DIR / "preproduccion" / "padron_2026_verificado.json"


# ---------------------------------------------------------------------------
# Firebase helpers
# ---------------------------------------------------------------------------
def _init_firestore():
    """Lazy-init Firebase and return Firestore client."""
    import firebase_admin
    from firebase_admin import credentials, firestore

    if not firebase_admin._apps:
        cred = credentials.ApplicationDefault()
        firebase_admin.initialize_app(cred, {"projectId": "suteba-2026"})

    return firestore.client()


def _fetch_collection(db, collection: str) -> dict[str, dict]:
    """Fetch every document in *collection* and return {doc_id: data}."""
    docs = db.collection(collection).stream()
    result = {}
    for doc in docs:
        data = doc.to_dict()
        result[doc.id] = data
    return result


# ---------------------------------------------------------------------------
# Core logic
# ---------------------------------------------------------------------------
def load_tasks() -> dict:
    """Load the local tasks.json generated by generate_verification_tasks."""
    if not TASKS_FILE.exists():
        print(f"ERROR: tasks.json not found at {TASKS_FILE}")
        sys.exit(1)

    with open(TASKS_FILE) as f:
        return json.load(f)


def build_verified_padron(
    tasks_data: dict,
    results: dict[str, dict],
    task_statuses: dict[str, dict],
    *,
    include_unverified: bool = False,
) -> dict:
    """Merge Firestore verification results with local OCR tasks.

    Returns the final padron dict ready for serialization.
    """
    registros: list[dict] = []
    completed_task_ids: set[str] = set()
    volunteer_ids: set[str] = set()

    tasks_by_id: dict[str, dict] = {t["id"]: t for t in tasks_data["tasks"]}

    # --- 1. Verified tasks (from verificacion_results) -----------------------
    for task_id, result in results.items():
        completed_task_ids.add(task_id)
        volunteer_name = result.get("volunteer_name", "")
        volunteer_id = result.get("volunteer_id", "")
        if volunteer_id:
            volunteer_ids.add(volunteer_id)

        source_image = result.get("image", "")
        # If result has no image field, fall back to the task's image
        if not source_image and task_id in tasks_by_id:
            source_image = tasks_by_id[task_id].get("image", "")

        for i, rec in enumerate(result.get("records", [])):
            registros.append({
                "dni": rec.get("documento", ""),
                "tipo": rec.get("tipo", "DNI"),
                "nombre": rec.get("nombre", ""),
                "escuela": rec.get("destino", ""),
                "source_image": source_image,
                "verified": True,
                "verified_by": volunteer_name,
                "page_row": rec.get("row", i + 1),
            })

    # --- 2. Unverified tasks (original OCR, optional) ------------------------
    if include_unverified:
        for task in tasks_data["tasks"]:
            if task["id"] in completed_task_ids:
                continue

            for i, rec in enumerate(task.get("records", [])):
                registros.append({
                    "dni": rec.get("documento", ""),
                    "tipo": rec.get("tipo", "DNI"),
                    "nombre": rec.get("nombre", ""),
                    "escuela": rec.get("destino", ""),
                    "source_image": task.get("image", ""),
                    "verified": False,
                    "verified_by": "",
                    "page_row": rec.get("row", i + 1),
                })

    # --- 3. Build verification summary ---------------------------------------
    total_tasks = tasks_data.get("total_tasks", len(tasks_data["tasks"]))
    completed = len(completed_task_ids)
    completion_rate = round(completed / total_tasks, 2) if total_tasks else 0.0

    padron = {
        "total_registros": len(registros),
        "verificacion": {
            "total_tasks": total_tasks,
            "completed_tasks": completed,
            "completion_rate": completion_rate,
            "volunteers": len(volunteer_ids),
            "exported_at": datetime.now(timezone.utc).isoformat(),
        },
        "registros": registros,
    }

    return padron


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------
def write_json(padron: dict, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        json.dump(padron, f, ensure_ascii=False, indent=2)
    print(f"  JSON written to {output_path} ({len(padron['registros'])} records)")


def write_csv(padron: dict, output_path: Path) -> None:
    csv_path = output_path.with_suffix(".csv")
    csv_path.parent.mkdir(parents=True, exist_ok=True)

    fieldnames = ["dni", "tipo", "nombre", "escuela", "source_image", "verified", "verified_by", "page_row"]

    with open(csv_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for reg in padron["registros"]:
            writer.writerow(reg)

    print(f"  CSV written to {csv_path} ({len(padron['registros'])} records)")


def print_stats(padron: dict) -> None:
    v = padron["verificacion"]
    total = padron["total_registros"]
    verified = sum(1 for r in padron["registros"] if r.get("verified"))
    unverified = total - verified

    print()
    print("=" * 60)
    print("  VERIFICATION EXPORT SUMMARY")
    print("=" * 60)
    print(f"  Total tasks:       {v['total_tasks']}")
    print(f"  Completed tasks:   {v['completed_tasks']}")
    print(f"  Completion rate:   {v['completion_rate']:.0%}")
    print(f"  Volunteers:        {v['volunteers']}")
    print(f"  Total records:     {total}")
    print(f"    Verified:        {verified}")
    print(f"    Unverified:      {unverified}")
    print(f"  Exported at:       {v['exported_at']}")
    print("=" * 60)
    print()


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(
        description="Export verified padron from Firestore",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--format",
        choices=["json", "csv"],
        default="json",
        help="Output format (default: json)",
    )
    parser.add_argument(
        "--include-unverified",
        action="store_true",
        help="Include unverified OCR records (marked verified=false)",
    )
    parser.add_argument(
        "--stats",
        action="store_true",
        help="Print summary stats only, don't write file",
    )
    args = parser.parse_args()

    # 1. Load local tasks
    print("Loading tasks.json...")
    tasks_data = load_tasks()
    print(f"  {tasks_data['total_tasks']} tasks, {tasks_data['total_records']} records")

    # 2. Fetch Firestore data
    print("Connecting to Firestore (project: suteba-2026)...")
    db = _init_firestore()

    print("Fetching verificacion_results...")
    results = _fetch_collection(db, "verificacion_results")
    print(f"  {len(results)} verified tasks")

    print("Fetching verificacion_tasks...")
    task_statuses = _fetch_collection(db, "verificacion_tasks")
    print(f"  {len(task_statuses)} task documents")

    # 3. Merge
    print("Building verified padron...")
    padron = build_verified_padron(
        tasks_data,
        results,
        task_statuses,
        include_unverified=args.include_unverified,
    )

    # 4. Stats
    print_stats(padron)

    # 5. Write output (unless --stats only)
    if args.stats:
        print("  --stats mode: no file written.")
        return

    if args.format == "csv":
        write_csv(padron, args.output)
    else:
        write_json(padron, args.output)

    print("\nDone.")


if __name__ == "__main__":
    main()
