#!/usr/bin/env python3
"""Upload verification task metadata to Firestore.

Reads tasks.json generated by generate_verification_tasks.py and uploads
each task's metadata (without the records array) to Firestore for the
volunteer verification webapp.

Usage:
    python -m tools.upload_to_firestore [--dry-run] [--clear]
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path

_FIREBASE_AVAILABLE = True
try:
    import firebase_admin
    from firebase_admin import credentials, firestore
except ImportError:
    _FIREBASE_AVAILABLE = False


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
TASKS_JSON = (
    BASE_DIR
    / "13_mayo_2026"
    / "padron_provisorio"
    / "webapp"
    / "public"
    / "data"
    / "verificacion"
    / "tasks.json"
)

# ---------------------------------------------------------------------------
# Firebase config
# ---------------------------------------------------------------------------

PROJECT_ID = "suteba-2026"
COLLECTION = "verificacion_tasks"
PROGRESS_DOC = "verificacion_progress/global"
BATCH_LIMIT = 500  # Firestore batch write limit


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_tasks() -> dict:
    """Load tasks.json and return the full object."""
    if not TASKS_JSON.exists():
        print(f"ERROR: tasks.json not found at {TASKS_JSON}")
        print("  Run: python -m tools.generate_verification_tasks first.")
        sys.exit(1)

    with open(TASKS_JSON) as f:
        data: dict = json.load(f)

    total_tasks = data.get("total_tasks", 0)
    tasks = data.get("tasks", [])

    if not tasks:
        print("ERROR: tasks.json has no tasks.")
        sys.exit(1)

    print(f"Loaded {len(tasks)} tasks ({total_tasks} declared) from tasks.json")
    return data


def build_task_doc(task: dict) -> dict:
    """Build a Firestore document from a task (excludes records)."""
    return {
        "task_id": task["id"],
        "image": task["image"],
        "ocr_page": task.get("ocr_page", 0),
        "total_records": task.get("total_records", 0),
        "calidad": task.get("calidad", ""),
        "priority": task.get("priority", "MEDIA"),
        "stats": task.get("stats", {}),
        "status": "pending",
        "assigned_to": None,
        "assigned_at": None,
        "completed_at": None,
    }


def build_progress_doc(tasks: list[dict]) -> dict:
    """Build the global progress document."""
    stats: dict[str, int] = {"alta": 0, "media": 0, "baja": 0}
    total_records = 0

    for task in tasks:
        priority = task.get("priority", "MEDIA").lower()
        stats[priority] = stats.get(priority, 0) + 1
        total_records += task.get("total_records", 0)

    return {
        "total_tasks": len(tasks),
        "total_records": total_records,
        "done": 0,
        "stats": stats,
    }


# ---------------------------------------------------------------------------
# Progress bar helper
# ---------------------------------------------------------------------------

def _progress_bar(current: int, total: int, width: int = 40) -> str:
    """Render an ASCII progress bar."""
    pct = current / total if total else 0
    filled = int(width * pct)
    bar = "#" * filled + "-" * (width - filled)
    return f"[{bar}] {current}/{total} ({pct:.0%})"


# ---------------------------------------------------------------------------
# Firestore operations
# ---------------------------------------------------------------------------

def get_db():
    """Initialize Firebase Admin and return Firestore client."""
    if not _FIREBASE_AVAILABLE:
        print("ERROR: firebase-admin is required.")
        print("  pip install firebase-admin")
        sys.exit(1)
    if not firebase_admin._apps:
        try:
            cred = credentials.ApplicationDefault()
            firebase_admin.initialize_app(cred, {"projectId": PROJECT_ID})
        except Exception as exc:
            print(f"ERROR: Failed to initialize Firebase Admin: {exc}")
            print()
            print("Make sure you have one of:")
            print("  - GOOGLE_APPLICATION_CREDENTIALS env var pointing to a service account key")
            print("  - gcloud auth application-default login")
            sys.exit(1)

    return firestore.client()


def clear_collection(db: firestore.firestore.Client) -> int:
    """Delete all documents in the verificacion_tasks collection.

    Returns the number of documents deleted.
    """
    print(f"Deleting all documents in '{COLLECTION}'...")
    deleted = 0
    batch = db.batch()
    batch_count = 0

    docs = db.collection(COLLECTION).stream()
    for doc in docs:
        batch.delete(doc.reference)
        batch_count += 1
        deleted += 1

        if batch_count >= BATCH_LIMIT:
            batch.commit()
            print(f"  Deleted {deleted} docs so far...")
            batch = db.batch()
            batch_count = 0

    if batch_count > 0:
        batch.commit()

    # Also delete the progress doc
    progress_ref = db.document(PROGRESS_DOC)
    progress_ref.delete()

    print(f"  Deleted {deleted} task documents + progress doc.")
    return deleted


def upload_tasks(
    db: firestore.firestore.Client,
    tasks: list[dict],
    progress_doc: dict,
) -> None:
    """Upload task metadata and progress document to Firestore."""
    total = len(tasks)
    uploaded = 0
    batch = db.batch()
    batch_count = 0

    print(f"\nUploading {total} tasks to '{COLLECTION}'...")
    t0 = time.monotonic()

    for task in tasks:
        ref = db.collection(COLLECTION).document(task["id"])
        doc = build_task_doc(task)
        batch.set(ref, doc)
        batch_count += 1
        uploaded += 1

        if batch_count >= BATCH_LIMIT:
            batch.commit()
            elapsed = time.monotonic() - t0
            print(f"\r  {_progress_bar(uploaded, total)}  ({elapsed:.1f}s)", end="", flush=True)
            batch = db.batch()
            batch_count = 0

    # Append the progress document to the final batch
    progress_ref = db.document(PROGRESS_DOC)
    batch.set(progress_ref, progress_doc)
    batch_count += 1

    if batch_count > 0:
        batch.commit()

    elapsed = time.monotonic() - t0
    print(f"\r  {_progress_bar(uploaded, total)}  ({elapsed:.1f}s)")
    print(f"\n  Uploaded {uploaded} task docs + progress/global in {elapsed:.1f}s")


# ---------------------------------------------------------------------------
# Dry-run output
# ---------------------------------------------------------------------------

def dry_run_report(tasks: list[dict], progress_doc: dict) -> None:
    """Print what would be uploaded without actually writing."""
    print("\n--- DRY RUN (no data will be written) ---\n")

    # Summary table by priority
    by_priority: dict[str, list[dict]] = {"ALTA": [], "MEDIA": [], "BAJA": []}
    for task in tasks:
        p = task.get("priority", "MEDIA")
        by_priority.setdefault(p, []).append(task)

    print("Tasks by priority:")
    for prio in ("ALTA", "MEDIA", "BAJA"):
        items = by_priority.get(prio, [])
        records = sum(t.get("total_records", 0) for t in items)
        print(f"  {prio:6s}: {len(items):4d} tasks, {records:6d} records")

    print(f"\nTotal: {len(tasks)} tasks, {progress_doc['total_records']} records")

    # Show first 5 tasks as sample
    print("\nSample documents (first 5):")
    for task in tasks[:5]:
        doc = build_task_doc(task)
        print(f"  /{COLLECTION}/{task['id']}")
        for k, v in doc.items():
            print(f"    {k}: {v!r}")
        print()

    print(f"Progress document (/{PROGRESS_DOC}):")
    for k, v in progress_doc.items():
        print(f"  {k}: {v!r}")

    print("\n--- END DRY RUN ---")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Upload verification task metadata to Firestore",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview what would be uploaded without writing to Firestore",
    )
    parser.add_argument(
        "--clear",
        action="store_true",
        help="Delete all existing task documents before uploading",
    )
    args = parser.parse_args()

    # Load data
    data = load_tasks()
    tasks: list[dict] = data["tasks"]
    progress_doc = build_progress_doc(tasks)

    # Dry run?
    if args.dry_run:
        dry_run_report(tasks, progress_doc)
        return

    # Real upload — connect to Firestore
    db = get_db()

    # Clear existing?
    if args.clear:
        answer = input(
            f"\nThis will DELETE all documents in '{COLLECTION}'. Continue? [y/N] "
        ).strip().lower()
        if answer != "y":
            print("Aborted.")
            return
        clear_collection(db)

    # Upload
    upload_tasks(db, tasks, progress_doc)

    print("\nDone.")


if __name__ == "__main__":
    main()
